### PR TITLE
finish removing neon

### PR DESCRIPTION
**Pull request by builderjer**

### CODE REVIEW

**Comment by builderjer** [comment]
not sure why the tests fail.  I have tried, but this was my first look at the tests.  The skill loads and works on raspbian-ovos

**Comment by JarbasAl** [comment]
This was meant as a PR for neon official skill, not intended to be a maintained fork, but seems it may take a while to drop the NeonSkill class so I think we can do this for now since the old Mycroft skill forks were archived

**Comment by builderjer** [comment]
Then can I merge?

**Comment by emphasize** [comment]
The first thing i see - that is probably consequetial -  is that a `test_fs` should hold the files wrote to disk.
I don't know how Neon and OVOS skill classes diverge, but with OVOS you can't simply do
https://github.com/OpenVoiceOS/skill-alerts/blob/83c9a717d6829492b9c95485de6ff0acc76ab962/test/test_skill.py#L74-L75

**Comment by emphasize** [comment]
also, watch out for timezones and testing locally. Sometimes utc is used, removing an alert instantly

**Comment by emphasize** [comment]
Just a heads up for everyone involved.
I'll do a sprint on my DAV skill-alerts to get another (potential) starting off point.

**Comment by JarbasAl** [comment]
replaced by #4

**Pull request closed without merging**
